dataset:
    data_path: sample_okvqa
    dataset_name: OKVQA
    split: test
    testing: False
    max_samples:
    batch_size: 1
    start_sample: 0

prompt: ./prompts/benchmarks/okvqa.prompt

results_dir: ./results/okvqa/

load_models:
    maskrcnn: False
    clip: False
    glip: True
    owlvit: False
    tcl: False
    gpt3_list: True
    gpt3_qa: True
    gpt3_guess: True
    depth: False
    blip: True
    saliency: False
    xvlm: True

fixed_code_file: ./prompts/fixed_code/blip2.prompt